#!/usr/bin/env python3
"""
Create patient_1.xlsx with the same columns as patients.xlsx and rows covering all scenarios
for testing: high/medium/low risk, SMS/Email/Call/WhatsApp/Pushover, consent, refill due, etc.
"""
from pathlib import Path
import pandas as pd

# Same columns as existing patients.xlsx (from utils.REQUIRED_EXCEL_COLUMNS / generate_patients_excel.EXCEL_COLUMNS)
COLUMNS = [
    "Member ID",
    "Patient Name",
    "Adherence Percentage",
    "Adeherence Percentage",
    "PDC Percentage",
    "Refill Days",
    "Patient Contact",
    "Patient EmailID",
    "City",
    "Medication Name",
    "EventDate",
    "NotificationSentOn",
    "NotificationSentAt",
    "NotificationStatus",
    "NotificationChannel",
    "NotificationMessageId",
    "RoutedToClinicianOn",
    "RoutedToClinicianNote",
    "AppreciationSentOn",
    "RiskScore",
    "RiskLabel",
    "ClinicianAssigned",
    "EscalationReason",
    "LastUpdated",
]

def _ts(days_ago=0):
    t = pd.Timestamp.now() - pd.Timedelta(days=days_ago)
    return t

def _nat():
    return pd.NaT

def scenario_rows():
    now = pd.Timestamp.now()
    event_today = now - pd.Timedelta(days=2)

    rows = [
        # 1. High risk: low adherence + refill overdue (0 days)
        {
            "Member ID": "MBR00001",
            "Patient Name": "Alice High-Risk",
            "Adherence Percentage": 35.0,
            "Adeherence Percentage": 35.0,
            "PDC Percentage": 35.0,
            "Refill Days": 0,
            "Patient Contact": "+1-555-100-1001",
            "Patient EmailID": "alice.highrisk@example.com",
            "City": "New York",
            "Medication Name": "Lisinopril 10mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 75,
            "RiskLabel": "High",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 2. High risk: refill in 3 days, low adherence
        {
            "Member ID": "MBR00002",
            "Patient Name": "Bob Refill-Soon",
            "Adherence Percentage": 42.0,
            "Adeherence Percentage": 42.0,
            "PDC Percentage": 42.0,
            "Refill Days": 3,
            "Patient Contact": "+1-555-100-1002",
            "Patient EmailID": "bob.refill@example.com",
            "City": "Los Angeles",
            "Medication Name": "Metformin 500mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "SMS",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 68,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 3. Medium risk
        {
            "Member ID": "MBR00003",
            "Patient Name": "Carol Medium",
            "Adherence Percentage": 65.0,
            "Adeherence Percentage": 65.0,
            "PDC Percentage": 65.0,
            "Refill Days": 14,
            "Patient Contact": "+1-555-100-1003",
            "Patient EmailID": "carol.medium@example.com",
            "City": "Chicago",
            "Medication Name": "Atorvastatin 20mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 42,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 4. Low risk / good adherence
        {
            "Member ID": "MBR00004",
            "Patient Name": "David Low-Risk",
            "Adherence Percentage": 92.0,
            "Adeherence Percentage": 92.0,
            "PDC Percentage": 92.0,
            "Refill Days": 45,
            "Patient Contact": "+1-555-100-1004",
            "Patient EmailID": "david.low@example.com",
            "City": "Houston",
            "Medication Name": "Amlodipine 5mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 12,
            "RiskLabel": "Low",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 5. Channel: Email only (no phone)
        {
            "Member ID": "MBR00005",
            "Patient Name": "Eve Email-Only",
            "Adherence Percentage": 48.0,
            "Adeherence Percentage": 48.0,
            "PDC Percentage": 48.0,
            "Refill Days": 5,
            "Patient Contact": "",
            "Patient EmailID": "eve.email@example.com",
            "City": "Phoenix",
            "Medication Name": "Omeprazole 20mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "Email",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 55,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 6. Channel: Call (voice)
        {
            "Member ID": "MBR00006",
            "Patient Name": "Frank Call-Preferred",
            "Adherence Percentage": 38.0,
            "Adeherence Percentage": 38.0,
            "PDC Percentage": 38.0,
            "Refill Days": 2,
            "Patient Contact": "+1-555-100-1006",
            "Patient EmailID": "frank.call@example.com",
            "City": "Boston",
            "Medication Name": "Losartan 50mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "Call",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 72,
            "RiskLabel": "High",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 7. Channel: WhatsApp
        {
            "Member ID": "MBR00007",
            "Patient Name": "Grace WhatsApp",
            "Adherence Percentage": 55.0,
            "Adeherence Percentage": 55.0,
            "PDC Percentage": 55.0,
            "Refill Days": 8,
            "Patient Contact": "+1-555-100-1007",
            "Patient EmailID": "grace.wa@example.com",
            "City": "Mumbai",
            "Medication Name": "Metoprolol 25mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "WhatsApp",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 48,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 8. Already notified today (governance: no duplicate)
        {
            "Member ID": "MBR00008",
            "Patient Name": "Henry Notified-Today",
            "Adherence Percentage": 40.0,
            "Adeherence Percentage": 40.0,
            "PDC Percentage": 40.0,
            "Refill Days": 4,
            "Patient Contact": "+1-555-100-1008",
            "Patient EmailID": "henry.today@example.com",
            "City": "Seattle",
            "Medication Name": "Gabapentin 300mg",
            "EventDate": event_today,
            "NotificationSentOn": now,
            "NotificationSentAt": now,
            "NotificationStatus": "Sent",
            "NotificationChannel": "SMS",
            "NotificationMessageId": "msg_12345",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 62,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 9. Notified in the past (cooldown scenario)
        {
            "Member ID": "MBR00009",
            "Patient Name": "Ivy Notified-Yesterday",
            "Adherence Percentage": 44.0,
            "Adeherence Percentage": 44.0,
            "PDC Percentage": 44.0,
            "Refill Days": 6,
            "Patient Contact": "+1-555-100-1009",
            "Patient EmailID": "ivy.yesterday@example.com",
            "City": "Denver",
            "Medication Name": "Sertraline 50mg",
            "EventDate": event_today,
            "NotificationSentOn": _ts(1),
            "NotificationSentAt": _ts(1),
            "NotificationStatus": "Sent",
            "NotificationChannel": "Email",
            "NotificationMessageId": "msg_67890",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 58,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 10. Refill days missing (optional column)
        {
            "Member ID": "MBR00010",
            "Patient Name": "Jack No-Refill-Days",
            "Adherence Percentage": 70.0,
            "Adeherence Percentage": 70.0,
            "PDC Percentage": 70.0,
            "Refill Days": pd.NA,
            "Patient Contact": "+1-555-100-1010",
            "Patient EmailID": "jack.norefill@example.com",
            "City": "Pune",
            "Medication Name": "Pantoprazole 40mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 32,
            "RiskLabel": "Low",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 11. App Push / Pushover channel
        {
            "Member ID": "MBR00011",
            "Patient Name": "Kate App-Push",
            "Adherence Percentage": 50.0,
            "Adeherence Percentage": 50.0,
            "PDC Percentage": 50.0,
            "Refill Days": 10,
            "Patient Contact": "+1-555-100-1011",
            "Patient EmailID": "kate.push@example.com",
            "City": "Richmond",
            "Medication Name": "Levothyroxine 50mcg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "App Push",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 52,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 12. Escalation / routed to clinician
        {
            "Member ID": "MBR00012",
            "Patient Name": "Leo Escalated",
            "Adherence Percentage": 28.0,
            "Adeherence Percentage": 28.0,
            "PDC Percentage": 28.0,
            "Refill Days": 0,
            "Patient Contact": "+1-555-100-1012",
            "Patient EmailID": "leo.escalated@example.com",
            "City": "Charlotte",
            "Medication Name": "Insulin Glargine",
            "EventDate": event_today,
            "NotificationSentOn": _ts(3),
            "NotificationSentAt": _ts(3),
            "NotificationStatus": "Sent",
            "NotificationChannel": "SMS",
            "NotificationMessageId": "msg_11111",
            "RoutedToClinicianOn": _ts(2),
            "RoutedToClinicianNote": "High risk; low adherence and refill overdue",
            "AppreciationSentOn": _nat(),
            "RiskScore": 82,
            "RiskLabel": "High",
            "ClinicianAssigned": "Dr. Smith",
            "EscalationReason": "High risk patient",
            "LastUpdated": now,
        },
        # 13. Appreciation sent (refill improved)
        {
            "Member ID": "MBR00013",
            "Patient Name": "Mia Appreciated",
            "Adherence Percentage": 88.0,
            "Adeherence Percentage": 88.0,
            "PDC Percentage": 88.0,
            "Refill Days": 30,
            "Patient Contact": "+1-555-100-1013",
            "Patient EmailID": "mia.appreciated@example.com",
            "City": "Austin",
            "Medication Name": "Empagliflozin 10mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": now,
            "RiskScore": 15,
            "RiskLabel": "Low",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 14. Phone only (no email)
        {
            "Member ID": "MBR00014",
            "Patient Name": "Nick Phone-Only",
            "Adherence Percentage": 58.0,
            "Adeherence Percentage": 58.0,
            "PDC Percentage": 58.0,
            "Refill Days": 7,
            "Patient Contact": "+1-555-100-1014",
            "Patient EmailID": "",
            "City": "San Diego",
            "Medication Name": "Warfarin 5mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "SMS",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 45,
            "RiskLabel": "Medium",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
        # 15. Very low adherence, refill overdue
        {
            "Member ID": "MBR00015",
            "Patient Name": "Olivia Critical",
            "Adherence Percentage": 18.0,
            "Adeherence Percentage": 18.0,
            "PDC Percentage": 18.0,
            "Refill Days": -2,
            "Patient Contact": "+1-555-100-1015",
            "Patient EmailID": "olivia.critical@example.com",
            "City": "Dallas",
            "Medication Name": "Apixaban 5mg",
            "EventDate": event_today,
            "NotificationSentOn": _nat(),
            "NotificationSentAt": _nat(),
            "NotificationStatus": "",
            "NotificationChannel": "",
            "NotificationMessageId": "",
            "RoutedToClinicianOn": _nat(),
            "RoutedToClinicianNote": "",
            "AppreciationSentOn": _nat(),
            "RiskScore": 90,
            "RiskLabel": "High",
            "ClinicianAssigned": "",
            "EscalationReason": "",
            "LastUpdated": now,
        },
    ]
    return rows


def main():
    base = Path(__file__).resolve().parent
    # Save in Data folder next to patients.xlsx
    out = base / "Data" / "patient_1.xlsx"
    out.parent.mkdir(parents=True, exist_ok=True)
    rows = scenario_rows()
    df = pd.DataFrame(rows, columns=COLUMNS)
    df.to_excel(out, index=False, engine="openpyxl")
    print(f"Created {out} with {len(df)} scenario rows and columns: {list(df.columns)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
